---
  title: "Data Products Assignment 1"
  output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Data are located here: https://github.com/planetsig/ufo-reports

```

## Date 2018/01/15
## UFO Sightings listed by longitude and latiude in NY. Hover over to view description of incident.

```{r Map, echo=FALSE, warning=FALSE, message=FALSE}

library(leaflet)

setwd("C:/Users/mlaud/Dropbox/R/Data Products")
UFOdf<-read.csv('ufo-scrubbed-geocoded-time-standardized.csv',header=FALSE)


#Note dataset does not display properly on github if entire list of sightings displayed. Need to choose a subset to reduce file size.

UFOdf<-UFOdf[UFOdf$V3=="ny",]
UFOdf<-UFOdf[!grepl("FAA Boston Cntr",UFOdf$V8),] #remove misclassification


my_Map<-leaflet() %>% #pipe command pass argument into line below
  addTiles() %>%
  addMarkers(lat=as.numeric(as.character(UFOdf$V10)),lng=as.numeric(as.character(UFOdf$V11)),label=UFOdf$V8,clusterOptions = markerClusterOptions())

my_Map


```
